name: guesser_game
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  presentation:
    path: packages/presentation


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.2.0
  injectable_generator: 1.5.4

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

